### ISSUE TITLE
Broken URL on Coiled / OSS Engineer

### ISSUE THREAD

**Issue by alexdesiqueira** [numfocus/jobs-board#10]
Hey everyone,
the URL on [Coiled / OSS Engineer](https://jobs.numfocus.org/job/2021-04-14_coiled),
![image](https://user-images.githubusercontent.com/5776022/119002013-59784880-b941-11eb-9ed6-df2dd3f29216.png)
is broken.
Instead of `https://coiled.io/jobs/`, it should point to `https://coiled.io/careers/`; this specific job is very likely the one listed at https://jobs.lever.co/coiled/b13ef99c-8825-4079-92f9-96b0ff223d62.

**Comment by stefanv** [comment]
Thanks, Alex, fixed and will be deployed in a minute or so.
