### ISSUE TITLE
Job desciptions are off-by-one

### ISSUE THREAD

**Issue by pavithraes** [numfocus/jobs-board#28]
In [the board](https://jobs.numfocus.org/), the description for arviz is shown in the nvidia card (and arviz has description about the spyder grant, which I'm guessing was the previous card):

<img width="1093" alt="Screenshot 2022-06-11 at 6 14 52 PM" src="https://user-images.githubusercontent.com/33131404/173188502-bb4b9ef6-894e-4532-a6bd-3ec3fd881749.png">

**Comment by pavithraes** [comment]
This is the same as #9 (sorry, I should've gone through the tracker before opening a new one!)

**Comment by stefanv** [comment]
Yikes, I thought I had fixed that! I'll take a look.

**Comment by stefanv** [comment]
Issue verified.
