### ISSUE TITLE
Jobs board not showing

### ISSUE THREAD

**Issue by melissawm** [numfocus/jobs-board#32]
Currently, the jobs board is actually showing up as empty on https://jobs.numfocus.org/

![Screenshot_20230207_163735](https://user-images.githubusercontent.com/3949932/217347926-8b9d4da7-f9ec-4b57-bbf0-a44d0cdc50c7.png)

The console is showing a couple of errors:

![Screenshot_20230207_163819](https://user-images.githubusercontent.com/3949932/217347872-b452aa02-66b7-404b-abd8-cc68a8b1e0e6.png)

**Comment by stefanv** [comment]
There are no unexpired jobs! Maybe I should print a message when that is the case?

**Comment by CAM-Gerlach** [comment]
To provide another data point, in FF 107.0.1 on Windows, I see the jobs briefly display successfully, but then the JS hits a couple of React errors and the jobs are no longer displayed:

|Loading|Loaded|
|---|---|
| ![image](https://user-images.githubusercontent.com/17051931/217357348-3a1681c0-7211-44ab-bc9a-a574dfcb3f78.png) | ![image](https://user-images.githubusercontent.com/17051931/217351056-52a90ab8-a46d-46cb-9a3a-3f527a1e3c30.png) |

**Comment by stefanv** [comment]
Behavior is correct, if undesirable. I can have it filter first and then display.

See also https://github.com/numfocus/jobs-board/pull/33

**Comment by melissawm** [comment]
Oh I see! Thanks @stefanv !

**Comment by stefanv** [comment]
It's a good question, how those jobs ever slip by, because the code is:

```js
  const jobs = filterJobs(jobData, formData);
```

and in `filterJobs`:

```js
const filterJobs = (jobs, filter) => {
  // Filter out expired jobs.  Use Howland Island timezone to ensure
  // that everyone sees the job on its last day.
  const today = new Date();
  jobs = jobs.filter((job) => new Date(`${job.expires}T23:59:59.999-12:00`) > today);
```
```

**Comment by CAM-Gerlach** [comment]
Also, from a UX perspective, the idiomatic pattern would be to always show _some_ kind of message confirming that no open jobs are available instead of just a blank screen, which (as can be seen by the multiple responses here) is interpreted by users as abnormal behavior of unclear provenance.

**Comment by stefanv** [comment]
Check out the new page ;)

**Comment by psobolewskiPhD** [comment]
As one of the confused people by the blank page, the banner is great—thanks!
But from the other screenshots, it looks like the expired jobs are there somewhere, so maybe it could be possible to still browse them, just for curiousity/archival? Like a checkbox "expired" in the filter?

**Comment by stefanv** [comment]
Yes, all the jobs are there, since they receive permalinks. I can add a button to the search box to show expired posts as you suggest.

**Comment by stefanv** [comment]
@psobolewskiPhD There you go: https://github.com/numfocus/jobs-board/pull/34

**Comment by psobolewskiPhD** [comment]
Love it! thanks!
Minor nitpick: I think there's a line break missing:
<img width="75" alt="image" src="https://user-images.githubusercontent.com/76622105/217364128-01c9fe72-6da6-4691-aba4-204358ed3275.png">

**Comment by stefanv** [comment]
They render side-by-side on a wide screen, and then start to wrap as the screen gets narrower. A simple bit of CSS would solve that, if someone wants to take a look.

**Comment by SahilSinghTomar** [comment]
we can decrease padding to the right so that full-time come in 1 line
