### ISSUE TITLE
Are volunteering positions eligible for the job board?

### ISSUE THREAD

**Issue by brosaplanella** [numfocus/jobs-board#47]
In the PyBaMM team we are about to advertise some volunteering positions (i.e. unpaid) for a fundraising lead, a communications lead and a community manager. Are unpaid positions eligible to be posted in the board or is it only for paid positions?

More details on the positions: https://github.com/pybamm-team/pybamm.org/blob/10fed6efb535aa75d1597546b4d29c77cc9b9f3c/content/news/2024/07/15/role-adverts.md

**Comment by stefanv** [comment]
As long as it explicitly states that it is a volunteer position, it should be fine.
