### ISSUE TITLE
Mismatch path 

### ISSUE THREAD

**Issue by uchiha-vivek** [numfocus/jobs-board#50]
**gatsby-node.esm.js**

import jobs from "./src/jobs";
import path from "path";

export const createPages = async ({ graphql, actions }) => {
  const { createPage } = actions;
  jobs.map((job) =>
    createPage({
      path: `job/${job.id}`,
      component: path.resolve('./src/pages/job.jsx'),
      context: {
        job
      }
    })
  );
}

Sir in the above code : 
import jobs from "./src/jobs" is incorrect , i think it should be ./src/ pages/job

Please check  it once !

**Comment by stefanv** [comment]
Why, is there a problem with the current build?
