### ISSUE TITLE
Job posts are messed up

### ISSUE THREAD

**Issue by rgommers** [numfocus/jobs-board#9]
- The Coiled post has a Julia language related description
- The Quansight post has Coiled content

<img width="801" alt="image" src="https://user-images.githubusercontent.com/98330/118376471-517a7a80-b5c8-11eb-96c6-702defc0bf0e.png">

**Comment by stefanv** [comment]
Interesting!  I wonder what happened there; it doesn't reproduce locally, but I see the issue online.

**Comment by stefanv** [comment]
I scoured the source and couldn't find the problem, so re-built the site and all looks good.  I'll keep an eye out in the future for something similar happening; thanks for the heads-up, Ralf.

**Comment by rgommers** [comment]
Thanks for the quick fix Stefan.
